
name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'npm'
      - run: npm i @typescript-eslint/parser @typescript-eslint/eslint-plugin eslint typescript
      - run: npx eslint src test
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'npm'
      - run: npm i prettier
      - run: npx eslint src test
      - run: npx prettier --check src
  test:
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Start CSS in the background
      run: npm run testServer &
    - name: Wait until the server has started
      run: >
        curl --output /dev/null --silent --head --fail --retry 30
        --retry-connrefused --retry-delay 0 -k http://localhost:3000/
    - name: Create test account credentials
      run: npx ts-node test/setup/createAccountCredentials.ts http://localhost:3000/ >> test/setup/.env
    - name: Load environment variables and run tests with coverage
      run: |
        npx dotenv -e ./test/setup/.env npm test -- --coverage
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    
